'use client';
import {useState} from 'react';
import {PawPrint,MapPin,Share2,ArrowLeft,Copy,Mail,Pencil,Trash2,Undo2,LoaderCircle} from 'lucide-react';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
export type Cat={id:string;names:string;location:string;notes:string;photos:string;created:string};
export default function CatDetail({cat,canEdit=false}:{cat:Cat;canEdit?:boolean}){
 const [profile,setProfile]=useState(cat),[selected,setSelected]=useState<string|null>(JSON.parse(cat.photos)[0]||null),[share,setShare]=useState(false),[message,setMessage]=useState('');
 const [editing,setEditing]=useState(false),[location,setLocation]=useState(cat.location),[notes,setNotes]=useState(cat.notes),[kept,setKept]=useState<string[]>(JSON.parse(cat.photos)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState<'save'|'delete'|null>(null);
 const names:string[]=JSON.parse(profile.names),photos:string[]=JSON.parse(profile.photos),visiblePhotos=editing?kept:photos;
 const active=selected&&visiblePhotos.includes(selected)?selected:visiblePhotos[0]||null;
 const url=typeof window!=='undefined'?window.location.href:'';
 async function nativeShare(){if(navigator.share){try{await navigator.share({title:`Meet ${names[0]} · Purrtrail`,url:window.location.href});}catch(e){if((e as Error).name!=='AbortError')setShare(true);}}else setShare(!share);}
 function edit(){setLocation(profile.location);setNotes(profile.notes);setKept(photos);setError('');setMessage('');setEditing(true);}
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/cats/'+profile.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({location,notes,photos:kept,originalPhotos:profile.photos,originalLocation:profile.location,originalNotes:profile.notes})});const d=await r.json() as Cat & {error?:string};if(!r.ok)throw Error(d.error);setProfile(d);setEditing(false);setSelected(kept[0]||null);setMessage('Changes saved.');setConfirm(null);}catch(e){setError((e as Error).message);setConfirm(null);}finally{setBusy(false);}}
 async function deleteCat(){setBusy(true);setError('');try{const r=await fetch('/api/cats/'+profile.id,{method:'DELETE'});const d=await r.json() as Cat & {error?:string};if(!r.ok)throw Error(d.error);window.location.assign('/');}catch(e){setError((e as Error).message);setConfirm(null);setBusy(false);}}
 function submit(e:React.FormEvent){e.preventDefault();if(kept.length<photos.length)setConfirm('save');else save();}
 return <><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><PawPrint/></span>purrtrail.</a><a className="account" href="/">My journal</a></header><main className="shell"><a className="back" href="/"><ArrowLeft size={17}/>Back to journal</a><div className="detail"><div>{active?<img className="detail-image" src={'/api/photos/'+active} alt={names[0]}/>:<div className="detail-image no-photo"><PawPrint size={46}/><p>No photos</p></div>}<div className="thumbnails">{(editing?photos:visiblePhotos).map((p,i)=><div className={'photo-edit-item '+(editing&&!kept.includes(p)?'pending-removal':'')} key={p}><button className={active===p?'selected':''} onClick={()=>setSelected(p)} disabled={editing&&!kept.includes(p)} aria-label={'View photo '+(i+1)}><img src={'/api/photos/'+p} alt={'Photo '+(i+1)}/></button>{editing&&<button className="remove-photo" type="button" disabled={busy} onClick={()=>setKept(kept.includes(p)?kept.filter(k=>k!==p):photos.filter(k=>kept.includes(k)||k===p))} aria-label={(kept.includes(p)?'Remove':'Restore')+' photo '+(i+1)}>{kept.includes(p)?<Trash2 size={15}/>:<Undo2 size={15}/>}{kept.includes(p)?'Remove':'Undo'}</button>}</div>)}</div>{editing&&<p className="hint">Photos marked for removal are only deleted when you save. You can keep the cat even with no photos.</p>}</div><article><div className="eyebrow">A LITTLE ENCOUNTER</div><h1>{names[0]}</h1>{names.length>1&&<div className="aliases">{names.slice(1).map(n=><span key={n}>{n}</span>)}</div>}
 {editing?<form onSubmit={submit} className="edit-cat"><h2>Edit your cat</h2><label>Location<input required maxLength={300} value={location} onChange={e=>setLocation(e.target.value)} disabled={busy}/></label><label>The little details<textarea rows={5} maxLength={3000} value={notes} onChange={e=>setNotes(e.target.value)} disabled={busy}/></label><div className="edit-actions"><button type="submit" className="primary" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:null}Save changes</button><button type="button" className="secondary-button" disabled={busy} onClick={()=>{setEditing(false);setError('');}}>Cancel</button></div></form>:<><p className="place"><MapPin size={18}/>{profile.location}</p><a className="text-button" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(profile.location)} target="_blank" rel="noreferrer">Open location in maps ↗</a><div className="story"><h2>The little details</h2><p>{profile.notes||'Sometimes a photo says it all.'}</p><small>Added {new Date(profile.created).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</small></div><div className="edit-actions"><button className="primary" onClick={nativeShare}><Share2 size={19}/>Share this cat</button>{canEdit&&<button className="secondary-button" onClick={edit}><Pencil size={17}/>Edit cat</button>}</div>{share&&<div className="share-options"><a href={'https://wa.me/?text='+encodeURIComponent(`Meet ${names[0]}! ${url}`)} target="_blank" rel="noreferrer">WhatsApp ↗</a><a href={'mailto:?subject='+encodeURIComponent(`Meet ${names[0]}`)+'&body='+encodeURIComponent(url)}><Mail size={17}/>Email</a><button onClick={async()=>{try{await navigator.clipboard.writeText(url);setMessage('Link copied!');}catch{setMessage('Copy the link from your browser address bar.');}}}><Copy size={17}/>Copy link</button></div>}</>}
 {canEdit&&<button className="delete-cat" disabled={busy} onClick={()=>setConfirm('delete')}><Trash2 size={16}/>Delete cat from journal</button>}{error&&<p role="alert" className="error">{error}</p>}<p role="status">{message}</p></article></div><footer><span><PawPrint size={16}/>App Created by Philip and Maxwell the Cat</span></footer></main>
 <AlertDialog open={confirm!==null} onOpenChange={open=>{if(!open&&!busy)setConfirm(null);}}><AlertDialogContent className="cat-confirm"><AlertDialogTitle>{confirm==='delete'?'Delete this cat?':'Delete the removed photos?'}</AlertDialogTitle><AlertDialogDescription>{confirm==='delete'?'This permanently deletes this cat and all its photos from your journal. Its shared link will stop working.':`Saving will permanently delete ${photos.length-kept.length} photo(s) and update the location and little details. This cannot be undone.`}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep editing</AlertDialogCancel><AlertDialogAction className="danger-button" disabled={busy} onClick={e=>{e.preventDefault();if(confirm==='delete')deleteCat();else save();}}>{busy?'Please wait…':confirm==='delete'?'Delete cat':'Save and delete photos'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}

