'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera, PawPrint, Plus, MapPin, ArrowUpRight, X, ImagePlus, LocateFixed, BookOpen, LoaderCircle} from 'lucide-react';
type Cat={id:string;names:string;location:string;photos:string;created:string};
export default function Journal({email}:{email:string|null}){
 const [cats,setCats]=useState<Cat[]>([]),[loading,setLoading]=useState(!!email),[error,setError]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[locating,setLocating]=useState(false),[location,setLocation]=useState(''),[files,setFiles]=useState<File[]>([]),[previews,setPreviews]=useState<string[]>([]);
 const camera=useRef<HTMLInputElement>(null),upload=useRef<HTMLInputElement>(null),dialog=useRef<HTMLDialogElement>(null);
 async function refresh(){setLoading(true);try{const r=await fetch('/api/cats');const d=await r.json();if(!r.ok)throw Error(d.error);setCats(d);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{if(email)refresh();},[email]);
 useEffect(()=>{const urls=files.map(f=>URL.createObjectURL(f));setPreviews(urls);return()=>urls.forEach(URL.revokeObjectURL);},[files]);
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
 function start(take=false){if(!email){window.location.href='/signin-with-chatgpt?return_to=/';return;}setError('');setOpen(true);if(take)camera.current?.click();}
 async function add(list:FileList|null){if(!list)return;setError('');const selected=Array.from(list);if(files.length+selected.length>6){setError('Choose up to 6 photos.');return;}const converted:File[]=[];try{for(const f of selected){if(!f.type.startsWith('image/'))throw Error('Please choose image files.'); const bitmap=await createImageBitmap(f);const canvas=document.createElement('canvas');const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/jpeg',.85));if(!blob)throw Error('Could not read this photo. Try a JPG or PNG.');converted.push(new File([blob],'cat.jpg',{type:'image/jpeg'}));}setFiles(prev=>[...prev,...converted]);}catch{setError('Could not read that photo. Please choose JPG, PNG or WebP.');}}
 async function locate(){setLocating(true);if(!navigator.geolocation){setError('Location is not supported. Enter a place below.');setLocating(false);return;}navigator.geolocation.getCurrentPosition(p=>{setLocation(`${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)}`);setLocating(false);},()=>{setError('Could not get your location. You can type a place instead.');setLocating(false);},{timeout:15000,enableHighAccuracy:true});}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');const data=new FormData(form);data.set('location',location);files.forEach(f=>data.append('photos',f));try{const r=await fetch('/api/cats',{method:'POST',body:data});const d=await r.json();if(!r.ok)throw Error(d.error);setOpen(false);setFiles([]);setLocation('');form.reset();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><PawPrint/></span>purrtrail<span className="brand-period">.</span></a><span className="top-caption">A little journal. A lot of cats.</span>{email?<a className="account" href="/signout-with-chatgpt?return_to=/" title={email}>Sign out</a>:<a className="account" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in ↗</a>}</header>
 <main className="shell"><div className="intro"><div><div className="eyebrow"><PawPrint size={15}/> THE CATS YOU CROSS PATHS WITH</div><h1>Small encounters.<br/><em>Unforgettable cats.</em></h1><p>Your own collection of whiskers, names and little stories.</p></div><button className="primary capture" onClick={()=>start(true)}><Camera size={21}/>Take Picture <Plus size={18}/></button></div>
 <div className="section-heading"><h2><BookOpen size={20}/> My cat journal <span className="count">{cats.length}</span></h2><button className="text-button" onClick={()=>start()}>Add a cat <Plus size={17}/></button></div>
 {error&&!open&&<div role="alert" className="error">{error} <button onClick={refresh}>Try again</button></div>}
 {loading?<div className="loading"><LoaderCircle className="spin"/>Opening your journal…</div>:cats.length?<div className="cat-grid">{cats.map(cat=><a className="cat-card" href={'/cat/'+cat.id} key={cat.id}><div className="cat-photo"><img src={'/api/photos/'+JSON.parse(cat.photos)[0]} alt={JSON.parse(cat.names)[0]}/><span className="photo-count">{JSON.parse(cat.photos).length} photos</span></div><div className="card-info"><h3>{JSON.parse(cat.names)[0]}<ArrowUpRight size={20}/></h3><p>{JSON.parse(cat.names).slice(1).join(' · ')||'A new familiar face'}</p><div className="place"><MapPin size={15}/>{cat.location}</div></div></a>)}</div>:<section className="empty"><div className="empty-photo"><img src="/garden-cat.jpg" alt="A ginger cat resting in a green garden"/><span className="photo-label"><PawPrint size={15}/> EVERY CAT HAS A STORY</span></div><div className="empty-copy"><span className="small-label">YOUR JOURNAL STARTS HERE</span><h2>Met someone<br/>purr-worthy?</h2><p>The garden regular. The café cat. The little stranger who made your day. Give them a place in your journal.</p><button className="primary" onClick={()=>start(true)}><Camera size={19}/>Meet your first cat</button><div className="mini-steps"><span>01 Snap</span><span>02 Name</span><span>03 Remember</span></div></div></section>}
 <footer><span><PawPrint size={16}/>For the love of little encounters.</span><span>Made for curious cat people.</span></footer></main>
 <input hidden ref={camera} type="file" accept="image/*" capture="environment" onChange={e=>{add(e.target.files);e.target.value='';}}/><input hidden ref={upload} type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{add(e.target.files);e.target.value='';}}/>
 <dialog ref={dialog} onCancel={e=>{if(busy)e.preventDefault();else setOpen(false);}} onClose={()=>setOpen(false)}><form onSubmit={save}><div className="dialog-head"><div><span className="eyebrow">A NEW LITTLE ENCOUNTER</span><h2>Who did you meet?</h2></div><button type="button" className="icon-button" aria-label="Close" disabled={busy} onClick={()=>setOpen(false)}><X/></button></div><div className="photo-tools"><button type="button" onClick={()=>camera.current?.click()}><Camera/>Take Picture</button><button type="button" onClick={()=>upload.current?.click()}><ImagePlus/>Upload photos</button></div><p className="hint">Up to 6 photos of the same cat.</p>{previews.length>0&&<div className="previews">{previews.map((url,i)=><div key={url}><img src={url} alt={'Selected cat photo '+(i+1)}/><button type="button" aria-label={'Remove photo '+(i+1)} onClick={()=>setFiles(files.filter((_,n)=>n!==i))}><X size={15}/></button></div>)}</div>}<label>Cat name(s)<input name="names" required maxLength={800} placeholder="Marmalade, Marmie, The garden boss"/></label><p className="hint">More than one name? Separate them with commas.</p><label>Where did you meet?<div className="location-field"><input required value={location} maxLength={300} onChange={e=>setLocation(e.target.value)} placeholder="A place, street or park"/><button type="button" onClick={locate} disabled={locating} aria-label="Use my current location">{locating?<LoaderCircle className="spin"/>:<LocateFixed/>}</button></div></label><p className="hint">Type a place or tap the location icon.</p><label>Anything else?<textarea name="notes" maxLength={3000} rows={3} placeholder="A favourite sunny spot, a distinctive marking, a very strong opinion…"/></label><p className="hint">Anyone with the profile link can see its photos, location and notes.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary save" disabled={busy||!files.length}>{busy?<LoaderCircle className="spin"/>:<PawPrint size={19}/>} {busy?'Saving your cat…':'Save to my journal'}</button></form></dialog></>;
}


